// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_bwh46.Models;

namespace Mission06_bwh46.Migrations
{
    [DbContext(typeof(MovieEntriesContext))]
    [Migration("20230213193148_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_bwh46.Models.MovieEntry", b =>
                {
                    b.Property<int>("entryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("entryId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            entryId = 1,
                            category = "Comedy",
                            director = "Peter Segal",
                            edited = false,
                            rating = "PG-13",
                            title = "Get Smart",
                            year = 2008
                        },
                        new
                        {
                            entryId = 2,
                            category = "Action",
                            director = "Ryan Coogler",
                            edited = false,
                            notes = "There is a sequel, and a third movie soon!",
                            rating = "PG-13",
                            title = "Creed",
                            year = 2015
                        },
                        new
                        {
                            entryId = 3,
                            category = "Romance/Comedy",
                            director = "Glenn Ficarra, John Requa",
                            edited = false,
                            rating = "PG-13",
                            title = "Crazy, Stupid, Love",
                            year = 2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
