// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_bwh46.Models;

namespace Mission06_bwh46Real.Migrations
{
    [DbContext(typeof(MovieEntriesContext))]
    partial class MovieEntriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_bwh46.Models.MovieEntry", b =>
                {
                    b.Property<int>("entryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("entryId");

                    b.HasIndex("categoryId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            entryId = 1,
                            categoryId = 2,
                            director = "Peter Segal",
                            edited = false,
                            rating = "PG-13",
                            title = "Get Smart",
                            year = 2008
                        },
                        new
                        {
                            entryId = 2,
                            categoryId = 3,
                            director = "Ryan Coogler",
                            edited = false,
                            notes = "There is a sequel, and a third movie soon!",
                            rating = "PG-13",
                            title = "Creed",
                            year = 2015
                        },
                        new
                        {
                            entryId = 3,
                            categoryId = 2,
                            director = "Glenn Ficarra, John Requa",
                            edited = false,
                            rating = "PG-13",
                            title = "Crazy, Stupid, Love",
                            year = 2011
                        });
                });

            modelBuilder.Entity("Mission06_bwh46Real.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            catName = "Action/Adventure"
                        },
                        new
                        {
                            categoryId = 2,
                            catName = "Comedy"
                        },
                        new
                        {
                            categoryId = 3,
                            catName = "Drama"
                        },
                        new
                        {
                            categoryId = 4,
                            catName = "Family"
                        },
                        new
                        {
                            categoryId = 5,
                            catName = "Horror/Suspense"
                        },
                        new
                        {
                            categoryId = 6,
                            catName = "Miscellaneous"
                        },
                        new
                        {
                            categoryId = 7,
                            catName = "Television"
                        },
                        new
                        {
                            categoryId = 8,
                            catName = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06_bwh46.Models.MovieEntry", b =>
                {
                    b.HasOne("Mission06_bwh46Real.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
